export const tableListHeadColumns = [
  { label: "번호", accessor: "id" },
  { label: "제목", accessor: "title" },
  { label: "글쓴이", accessor: "author" },
  { label: "날짜", accessor: "dateTime" },
  { label: "추천", accessor: "recommand" },
  { label: "조회", accessor: "watch" },
];

export const tableList = [
  {
    id: 1,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 2,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 3,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 4,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 5,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 6,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 7,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 8,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 9,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 10,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 11,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 12,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 13,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 14,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 15,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 16,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 17,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 18,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 19,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
  {
    id: 20,
    title: "해커에게 탈취 자금 90% 반환 요청",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    recommand: "999",
    watch: "99",
  },
];

export const tableNews = [
  {
    id: 1,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 2,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 3,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 4,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 5,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 6,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 7,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 8,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 9,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 10,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 11,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
];

export const tableChart = [
  {
    id: 1,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 2,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 3,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 4,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 5,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 6,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 7,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 8,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 9,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 10,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 11,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://v1.tailwindcss.com/img/card-top.jpg",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
];

export const tableAnalyze = [
  {
    id: 1,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 2,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 3,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 4,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 5,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 6,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 7,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 8,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 9,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 10,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 11,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://plus.unsplash.com/premium_photo-1683141154082-324d296f3c66?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
];

export const tableMarket = [
  {
    id: 1,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 2,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 3,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 4,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 5,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 6,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 7,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 8,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 9,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 10,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 11,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
  {
    id: 12,
    title: "Noteworthy technology acquisitions 2021",
    author: "typicode",
    dateTime: "2022-12-31 00:00:00",
    tag: "분석",
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1480&amp;q=80",
    recommand: "999",
    watch: "99",
    contents:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima distinctio ea natus at officia sapiente obcaecati dolorum inventore quo debitis velit omnis, aliquam perspiciatis tempora quasi quis consequatur et nisi mollitia unde voluptas eveniet animi. Voluptas vero debitis at quisquam",
  },
];
