import "../styles/globals.css";

export const metadata = {
  title: `CSI-Play `,
  description: "Generated by CSI-Play",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-300 text-sm   mx-auto">{children}</body>
    </html>
  );
}
